version: "3.9"

services:
  postgres:
    build: ./database
    container_name: progrexa-postgres
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy

  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8002:8000"
    depends_on:
      postgres:
        condition: service_healthy

  task-service:
    build: ./task-service
    env_file:
      - ./task-service/.env
    ports:
      - "8003:8000"
    depends_on:
      postgres:
        condition: service_healthy

  schedule-service:
    build: ./schedule-service
    env_file:
      - ./schedule-service/.env
    ports:
      - "8004:8000"
    depends_on:
      postgres:
        condition: service_healthy

  time-tracker-service:
    build: ./time-tracker-service
    env_file:
      - ./time-tracker-service/.env
    ports:
      - "8005:8000"
    depends_on:
      postgres:
        condition: service_healthy

  analytics-service:
    build: ./analytics-service
    env_file:
      - ./analytics-service/.env
    ports:
      - "8006:8000"
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    env_file:
      - ./notification-service/.env
    ports:
      - "8007:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - task-service
      - schedule-service
      - time-tracker-service
      - analytics-service
      - notification-service
      - user-service

volumes:
  pgdata:
